//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YchetStudentov.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Poseshaemost
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Poseshaemost()
        {
            this.Sost_Poseshaem = new HashSet<Sost_Poseshaem>();
        }
    
        public int ID { get; set; }
        public System.DateTime Data_ { get; set; }
        public Nullable<int> IDPreopod { get; set; }
        public Nullable<int> IDPredmeta { get; set; }
    
        public virtual Prepodovatel Prepodovatel { get; set; }
        public virtual Predmet Predmet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sost_Poseshaem> Sost_Poseshaem { get; set; }
    }
}
