//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YchetStudentov.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prepodovatel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prepodovatel()
        {
            this.Poseshaemost = new HashSet<Poseshaemost>();
        }
    
        public int ID { get; set; }
        public string Fam { get; set; }
        public string Imya { get; set; }
        public string Otch { get; set; }
        public string Loginn { get; set; }
        public string Pas { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Poseshaemost> Poseshaemost { get; set; }
    }
}
