//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YchetStudentov.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sost_Poseshaem
    {
        public int ID { get; set; }
        public Nullable<int> IDPoseshaem { get; set; }
        public Nullable<int> IDStud { get; set; }
    
        public virtual Poseshaemost Poseshaemost { get; set; }
        public virtual Students Students { get; set; }
    }
}
