//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YchetStudentov.Model.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Students()
        {
            this.Sost_Poseshaem = new HashSet<Sost_Poseshaem>();
        }
    
        public int ID { get; set; }
        public string Fam { get; set; }
        public string Imya { get; set; }
        public string Otch { get; set; }
        public string Seria_Stud_Bil { get; set; }
        public string Nomer_Stud_Bil { get; set; }
        public System.DateTime Birth_date { get; set; }
        public Nullable<int> IDGruppi { get; set; }
    
        public virtual Gruppa Gruppa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sost_Poseshaem> Sost_Poseshaem { get; set; }
    }
}
